/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["selector", '[data-theme="dark"]'],
  content: ["./templates/**/*.html", "./static/js/**/*.js", "./src/ts/**/*.ts"],
  theme: {
    extend: {
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
      },
      colors: {
        background: "#f6f6f8",
        "on-background": "#0f172a",
        "on-surface": "#0f172a",
        "on-surface-variant": "#64748b",
        surface: "#ffffff",
        "surface-bright": "#ffffff",
        "surface-dim": "#f6f6f8",
        "surface-variant": "#f1f5f9",
        "surface-container": "#f1f3f9",
        "surface-container-low": "#f8f9fc",
        "surface-container-high": "#e8ebf4",
        "surface-container-highest": "#e1e4ef",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#135bec",
        primary: "#135bec",
        "on-primary": "#ffffff",
        "primary-container": "#eef2ff",
        "on-primary-container": "#1e40af",
        "primary-fixed": "#dbeafe",
        "primary-fixed-dim": "#bfdbfe",
        "on-primary-fixed": "#1e3a8a",
        "on-primary-fixed-variant": "#1d4ed8",
        secondary: "#64748b",
        "on-secondary": "#ffffff",
        "secondary-container": "#f1f5f9",
        "on-secondary-container": "#1e293b",
        "secondary-fixed": "#e2e8f0",
        "secondary-fixed-dim": "#cbd5e1",
        "on-secondary-fixed": "#0f172a",
        "on-secondary-fixed-variant": "#334155",
        tertiary: "#f59e0b",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#fef3c7",
        "on-tertiary-container": "#92400e",
        "tertiary-fixed": "#fef3c7",
        "tertiary-fixed-dim": "#fde68a",
        "on-tertiary-fixed": "#451a03",
        "on-tertiary-fixed-variant": "#b45309",
        error: "#ef4444",
        "on-error": "#ffffff",
        "error-container": "#fee2e2",
        "on-error-container": "#991b1b",
        outline: "#cbd5e1",
        "outline-variant": "#e2e8f0",
        "inverse-surface": "#1e293b",
        "inverse-on-surface": "#f1f5f9",
        "inverse-primary": "#93c5fd",
        pocket: {
          bg: "#f6f6f8",
          primary: "#135bec",
          surface: "#ffffff",
          "surface-container": "#f1f3f9",
          "surface-high": "#e8ebf4",
          outline: "#cbd5e1",
          muted: "#64748b",
          ink: "#0f172a",
        },
      },
      borderRadius: {
        pocket: "0.75rem",
        "pocket-lg": "1rem",
        "pocket-xl": "1.5rem",
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};
