/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        "surface-container": "#f1f3f9",
        "surface-container-highest": "#e1e4ef",
        "on-secondary-container": "#1e293b",
        "primary-fixed": "#dbeafe",
        "on-tertiary-container": "#92400e",
        "surface-bright": "#ffffff",
        "surface-container-low": "#f8f9fc",
        "tertiary-fixed-dim": "#fde68a",
        "on-error-container": "#991b1b",
        "primary-container": "#eef2ff",
        "secondary-container": "#f1f5f9",
        error: "#ef4444",
        "inverse-surface": "#1e293b",
        "surface-variant": "#f1f5f9",
        "outline-variant": "#e2e8f0",
        "on-secondary": "#ffffff",
        background: "#f6f6f8",
        "on-surface": "#0f172a",
        "on-tertiary-fixed-variant": "#b45309",
        "on-primary-container": "#1e40af",
        surface: "#ffffff",
        "on-tertiary-fixed": "#451a03",
        "on-tertiary": "#ffffff",
        primary: "#135bec",
        secondary: "#64748b",
        "on-secondary-fixed": "#0f172a",
        "on-primary": "#ffffff",
        "primary-fixed-dim": "#bfdbfe",
        "on-primary-fixed-variant": "#1d4ed8",
        "surface-tint": "#135bec",
        "secondary-fixed": "#e2e8f0",
        tertiary: "#f59e0b",
        "surface-dim": "#f6f6f8",
        "inverse-primary": "#93c5fd",
        "error-container": "#fee2e2",
        "on-secondary-fixed-variant": "#334155",
        "on-background": "#0f172a",
        outline: "#cbd5e1",
        "surface-container-high": "#e8ebf4",
        "on-surface-variant": "#64748b",
        "surface-container-lowest": "#ffffff",
        "on-error": "#ffffff",
        "inverse-on-surface": "#f1f5f9",
        "tertiary-container": "#fef3c7",
        "secondary-fixed-dim": "#cbd5e1",
        "on-primary-fixed": "#1e3a8a",
        "tertiary-fixed": "#fef3c7",
      },
      fontFamily: {
        headline: ["Inter_700Bold", "Inter_600SemiBold", "System"],
        body: ["Inter_400Regular", "System"],
        label: ["Inter_500Medium", "System"],
      },
      borderRadius: {
        DEFAULT: "4px",
        lg: "8px",
        xl: "12px",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
